Update .github/actions/deploy-my-kibana/action.yml

diff --git a/.github/actions/deploy-my-kibana/action.yml b/.github/actions/deploy-my-kibana/action.yml
--- a/.github/actions/deploy-my-kibana/action.yml
+++ b/.github/actions/deploy-my-kibana/action.yml
@@ -67,9 +67,10 @@ runs:
             echo "CLUSTER=stateless-oblt" >> $GITHUB_ENV
             exit 0
           fi
-          STATUS="#### You cannot deploy your PR when targeting a branch other than main :broken_heart:"
-          echo "${STATUS}" >> $GITHUB_STEP_SUMMARY
-          echo "::setFailed::${STATUS}"
+          MESSAGE="You cannot deploy your PR when targeting a branch other than main"
+          echo "#### :broken_heart: ${MESSAGE}" >> $GITHUB_STEP_SUMMARY
+          echo "::error::${MESSAGE}"
+          exit 1
         fi
         if [ "${TARGET_BRANCH}" == 'main' ] ; then
           echo "CLUSTER=edge-lite-oblt" >> $GITHUB_ENV
