support for BUILD_ENV_VARS

diff --git a/.github/actions/buildkite/action.yml b/.github/actions/buildkite/action.yml
--- a/.github/actions/buildkite/action.yml
+++ b/.github/actions/buildkite/action.yml
@@ -30,6 +30,9 @@ inputs:
     description: 'Whether to wait for the build to finish.'
     default: false
     required: false
+  buildEnvVars:
+    description: 'Additional environment variables to set on the build.'
+    required: false
 
 runs:
   using: "composite"
@@ -53,13 +56,13 @@ runs:
           #
           # ignore_pipeline_branch_filters: By default Buildkite works only on master. As we want
           #                                 to use different branch names, we have to set this.
+
           JSON=$(
             jq -c -n \
               --arg COMMIT  "${{ github.sha }}" \
               --arg BRANCH  "main" \
               --arg COMMIT_AUTHOR "${{ github.event.head_commit.author.name }}" \
               --arg COMMIT_MSG "${{ github.event.head_commit.message }}" \
-              --arg DRA_BRANCH "main" \
               '{
                 "commit": $COMMIT,
                 "branch": $BRANCH,
@@ -67,12 +70,19 @@ runs:
                   "name": $COMMIT_AUTHOR,
                 },
                 "message": $COMMIT_MSG,
-                "env":  {
-                  "DRA_BRANCH": $DRA_BRANCH
-                },
                 "ignore_pipeline_branch_filters": true
               }'
           )
+
+          # Merge in the build environment variables, if they specified any
+          if [[ -n "${{ inputs.buildEnvVars }}" ]]; then
+            if ! JSON=$(echo "$JSON" | jq -c --argjson BUILD_ENV_VARS "${{ inputs.buildEnvVars }}" '. + {env: $BUILD_ENV_VARS}'); then
+              echo ""
+              echo "Error: BUILD_ENV_VARS provided invalid JSON: ${{ inputs.buildEnvVars }}"
+              exit 1
+            fi
+          fi
+
           RESP=$(curl \
             --no-progress-meter \
             -H "Authorization: Bearer ${{ env.BUILDKITE_API_ACCESS_TOKEN }}" \
