feat: archive test results

diff --git a/.github/workflows/pytest_otel.yml b/.github/workflows/pytest_otel.yml
--- a/.github/workflows/pytest_otel.yml
+++ b/.github/workflows/pytest_otel.yml
@@ -32,3 +32,8 @@ jobs:
         run: make -C resources/scripts/pytest_otel test
       - name: it-test
         run: make -C resources/scripts/pytest_otel it-test
+      - uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results
+          path: resources/scripts/pytest_otel/**/junit-*.xml
